cambios egoi-2022
FOPInformatica/FOPInformatica.github.io pull request #42
Opened 2022-09-07 05:49 UTC by alucard451

![imagen](https://user-images.githubusercontent.com/100726223/188798500-2e356ac8-34c9-4054-a0c1-1cf7e0aa4fdc.png)
![imagen](https://user-images.githubusercontent.com/100726223/188798555-130f22f6-bac7-4a4e-a90c-5bff9438528c.png)
![imagen](https://user-images.githubusercontent.com/100726223/188798605-4268f185-60ae-4fb7-b54f-334dbed96daa.png)

2022-09-07 19:29 UTC, a20012251 requested changes
tienes que eliminar todas las referencias a la IOI y cambiarlas por EGOI

2022-09-07 19:29 UTC, a20012251 commented on ioi-2022.html
> +  Cuentas a nombre de Walter Erquínigo
Cuentas a nombre de Walter Erquínigo, tesorero de la FOPI.

2022-09-07 19:29 UTC, a20012251 commented on ioi-2022.html
>      <div>International Olympiad in Informatics</div>
Usa el estilo de CSS `word-wrap: break-word` para que cuando la línea haga wrap (se parta en 2), no se parta en medio de una palabra, que es lo que sucede en tu screenshot, de la palabra "in" es partida en dos

2022-09-07 19:29 UTC, a20012251 commented on ioi-2022.html
>      <div class="ioi2022-contact" id="ioi2022-collect">
esto debe egoi2022 en los identificatores. La líneas de arriba tambien deben hacer referencia a la EGOI y no a la IOI

2022-09-07 22:41 UTC, alucard451 commented
![imagen](https://user-images.githubusercontent.com/100726223/188992658-797ef62b-69cd-445a-8a7e-a9d6d1e9d2b5.png)
aun esta pendiente el acomodar bien los titulos
![imagen](https://user-images.githubusercontent.com/100726223/188992703-9902f64d-c93d-4bdb-bbab-86e1df67bd4e.png)
creo que se deben de hacer cambios en esa parte, en especial donde da el link al pdf
![imagen](https://user-images.githubusercontent.com/100726223/188992831-dd064f23-0a1d-40de-b8ab-3a07df75ec27.png)

2022-09-08 17:25 UTC, a20012251 approved these changes

2022-09-08 17:25 UTC, merged